### ISSUE TITLE
Probleme mit PHP 8.1

### ISSUE THREAD

**Issue by auto-scroll** [clickpress/contao-clickpress-grid#6]
Hallo,
im Contao Manager erhalte ich folgende Fehlermeldung:
`In InitCommand.php line 909:
                                                                               
  Package clickpress/contao-clickpress-grid has requirements incompatible with your PHP version, PHP extensions and Composer version:                     
    - clickpress/contao-clickpress-grid 1.4.1 requires php ^7.1 which does not match your installed version 8.1.2.`

Contao 4.13
PHP 8.1

Gruß Michael

**Comment by stefansl** [comment]
Hi Michael, danke für den Hinweis. Der Fix war schon drin, aber noch nicht released. Probier bitte jetzt mal ein Update

**Comment by auto-scroll** [comment]
Passt!
Wunderbar, vielen Dank!
