### ISSUE TITLE
Required PHP-Version

### ISSUE THREAD

**Issue by syntaxys** [clickpress/contao-clickpress-grid#9]
Not every provider offers PHP 8.1 and not every other extension is prepared for this version. In most of the Contao installations I manage, I cannot currently update to version 1.5 of clickpress-grid.

**Comment by jaynoe** [comment]
Well you can still use the version 1.4.3 for PHP 7 - in 1.5 only the Contao 5 support was given. The functionality between 1.4.3 and 1.5 should be the same.

**Comment by Anke** [comment]
I'm just testing Clickpress Grid (very neat!!! and already star-rated) version 1.5 running with Contao 4.13.21 and PHP 8.1. 

No errors except Firefox console reports source map warnings:
```
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1f7e6221-8f86-4d44-815b-34534ce599d1/model/static/DOMPurify/purify.min.js
Source-Map-Adresse: purify.min.js.map

```
```
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://xxx.de/assets/css/clickpress-grid.css-f54166ac.css
Source-Map-Adresse: clickpress-grid.css.map

```

**Comment by stefansl** [comment]
Hi Anke, please open a new Issue for this.
